### ISSUE TITLE
Add extra space at the end of the ticket

### ISSUE THREAD

**Issue by GODAsderel** [Hubertformin/electron-pos-printer#19]
![d1f43e20cfc122135e4117f90ecf044c](https://user-images.githubusercontent.com/32823221/95119753-c50ffb80-074c-11eb-9902-4bef85a22d6e.png)
I need to add a margin at the bottom so it has an extra white space. I tried putting extra empty rows, &nbsp; and other kind of tricks but I can't find a way...

**Comment by Hubertformin** [comment]
Hello @GODAsderel ,
From your screenshot, I believe you're using a type `table`, did you try the table style?
example:
`
{
       type: 'table',
       // style the table
       style: 'margin-bottom: 184px',
    }`

**Comment by GODAsderel** [comment]
Yes, I'm using the type table, and I'm using css: to add the styles, I don't know why it also adds like a margin-bottom for default.
![4e3e6953-93e9-4344-a79d-9ef3b42776ea](https://user-images.githubusercontent.com/32823221/95124778-399a6880-0754-11eb-9e77-51b5dddbe11b.jpg)
`css: {"width":"100%","font-weight": "500","font-family": "Arial", "border-spacing":"0","margin-bottom":"0px","margin-top":"0px" }`

**Comment by GODAsderel** [comment]
`data.push({
      type: 'table',
      // style the table
      // style: 'margin-bottom: 1px !important',
      css: {"width":"100%","font-weight": "500","font-family": "Arial", "border-spacing":"0","margin-bottom":"0px","margin-top":"0px" },
      // list of the columns to be rendered in the table header
      // multi dimensional array depicting the rows and columns of the table body
      tableBody: [[{
        type: 'text',
        value: 'Mesa: ' + arg.info.mesa,
        style: `text-align:left;`,
        css: {"font-weight": "500", "font-size": "12px"}
      },{
        type: 'text',
        value: arg.info.fecha ,
        style: `text-align:left;`,
        css: {"font-weight": "500", "font-size": "12px"}
      }],[{
        type: 'text',
        value: 'Camarero: ' + arg.info.camarero.name,
        style: `text-align:left;`,
        css: {"font-weight": "500", "font-size": "12px"}
      },{
        type: 'text',
        value: arg.info.hora ,
        style: `text-align:left;`,
        css: {"font-weight": "500", "font-size": "12px"}
      }],[{
        type: 'text',
        value: 'Factura: ' + arg.info.idFactura,
        style: `text-align:left;`,
        css: {"font-weight": "500", "font-size": "12px"}
      }]],
      // list of columns to be rendered in the table footer
      // custom style for the table header
      // custom style for the table body
      tableBodyStyle: 'line-height: 0; text-align:center;'
      // custom style for the table footer
  })`

This is the code for the first table which includes Mesa, Camarero, Factura and the hour and time.

**Comment by Hubertformin** [comment]
Yes, you are right. I've fixed it, update to the latest version, you should have your problem solved!

**Comment by GODAsderel** [comment]
It's still not working, I did a npm i electron-pos-printer@latest and it still isn't working.

**Comment by GODAsderel** [comment]
Okey I fixed it, just delete `<div style="min-height:100px;">` from body-init.js and the case:'table'

**Comment by Hubertformin** [comment]
Hello,
Sorry for my late reply
I’ll do the changes by the end of today
